- name: update yum cache
  yum:
    update_cache: yes

- name: install python-pip
  become: yes
  yum:
    name: python3-pip
    state: present

- name: update pip
  ansible.builtin.shell: "sudo pip3 install --upgrade pip"

- name: install Python packages
  become: yes
  pip:
    name: psycopg2-binary
    executable: pip3

- name: install Python packages
  become: yes
  pip: "name={{ item }}  state=present"
  with_items:
    - psycopg2

- name: install PostgreSQL
  become: yes
  yum:
    name: postgresql-server.x86_64
    state: present

- name: set private IP to variable
  set_stats:
    data:
      DB_addr: "{{ host_private }}"
