- name: allow TCP access to 22 port
  ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: allow TCP access to 8080 port
  ufw:
    rule: allow
    port: '8080'
    proto: tcp
    state: enabled
